<?php

namespace FaarenTech\LaravelCustomUuids\Models;

use Illuminate\Database\Eloquent\Model as BaseModel;

abstract class UuidModel extends BaseModel
{
    /**
     * The prefix used by this model
     *
     * @var string $uuidPrefix
     */
    protected static string $uuidPrefix = "";

    protected $primaryKey = "uuid";

    public static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
    }

    public function exampleFunction(): string
    {
        return "Foooo";
    }
}
